version: '3.7'


services:

########################## Jenkins:lts #########################
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: "no"
    volumes: 
      - /Users/enggalilioo/projects/home/jenkins_home:/var/jenkins_home
    ports: 
      - 8080:8080
      - 50000:50000
    

########################## Nexus OSS3 ##########################
  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    restart: "no"
    volumes: 
      - /Users/enggalilioo/projects/home/nexus_home:/nexus-data
    ports: 
      - 8081:8081

########################## SonarQube ##########################
  sonar:
    image: sonarqube:lts
    container_name: sonarqube
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    restart: "no"
    volumes: 
      - /Users/enggalilioo/projects/home/sonar_home/conf:/opt/sonarqube/conf
      - /Users/enggalilioo/projects/home/sonar_home/extensions:/opt/sonarqube/extensions
      - /Users/enggalilioo/projects/home/sonar_home/logs:/opt/sonarqube/logs
      - /Users/enggalilioo/projects/home/sonar_home/data:/opt/sonarqube/data
    ports: 
      - 9000:9000



    
    